[package]
name = "stm32-quadcopter"
version = "0.1.0"
authors = ["Andrey Kiyko <eb08a167@gmail.com>"]
edition = "2018"

[dependencies]
cortex-m = "0.6.3"
cortex-m-rt = "0.6.12"
panic-halt = "0.2.0"
stm32f4 = { version = "0.11.0", features = ["stm32f446", "rt"] }

[profile.release]
lto = true
